services:
  db:
    image: postgres:16
    container_name: nexa-db-local
    environment:
      POSTGRES_DB: ${DB_DATABASE:-nexa}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
